variables:
  SLACK_API_TOKEN: $SLACK_API_TOKEN
  GITLAB_API_TOKEN: $GITLAB_API_TOKEN
  PROJECT_ID: "vish-381308"
  REGION: "us-west1-c"

deploy_function:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo $GCLOUD_SERVICE_KEY_JSON > /tmp/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud functions deploy Slyncops \
        --runtime python38 \
        --trigger-http \
        --allow-unauthenticated \
        --set-env-vars SLACK_API_TOKEN="$SLACK_API_TOKEN",GITLAB_API_TOKEN="$GITLAB_API_TOKEN" \
        --project $PROJECT_ID \
        --region $REGION
  only:
    - main
